[![Abrir en Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/UN-GCPDS/ProcesamientoDigitalImagenes/blob/main/Clase%201/Clase%201%20-%20Python_Numpy_Matplotlib.ipynb)


<img src="https://www.funcionpublica.gov.co/documents/d/guest/logo-universidad-nacional" alt="Logo UNAL" width="600"/>

### **Universidad Nacional de Colombia sede Manizales**
#### Facultad de ingeniería y arquitectura
#### Departamento de ingeniería eléctrica, electrónica y computación
#### *Procesamiento Digital de Imágenes*

#### Profesor: Lucas Iturriago
#### Monitora: Isabella Valero Mora - lvalerom@unal.edu.co

## Python

### 1.1 Breve introducción al lenguaje y ecosistema

#### ¿Qué es Python?

Python es un lenguaje de programación de alto nivel, interpretado y multiplataforma, creado por **Guido van Rossum** en 1991.
Se caracteriza por:

* **Simplicidad y legibilidad**: sintaxis clara y cercana al lenguaje natural.
* **Versatilidad**: se usa en ciencia de datos, web, automatización, inteligencia artificial, etc.
* **Gran ecosistema de librerías**: `numpy`, `pandas`, `matplotlib`, `scikit-learn`, `tensorflow`, entre muchas otras.
* **Comunidad activa**: millones de desarrolladores contribuyen a su crecimiento.

---

#### Hola Mundo en Python

In [ ]:
print("Hola, mundo")

#### Interpretado vs compilado

* Python es **interpretado**: se ejecuta línea por línea en un intérprete (como `python` o `ipython`).
* Esto permite probar ideas rápidamente, aunque puede ser más lento que lenguajes compilados como C o Java.

Ejemplo: 

In [ ]:
2 + 3

nombre = "Lucas"
print(nombre)

#### Manejo de librerías

Python utiliza **módulos** y **paquetes** para organizar y reutilizar código.
Las librerías se instalan usualmente con `pip`:

```bash
pip install python_librarie
```

Luego se importan en el programa:

```python
import python_librarie as pl
```

### 1.2 Variables y tipos de datos básicos

#### ¿Qué es una variable?

Una **variable** es un nombre que hace referencia a un valor en memoria.
En Python no necesitas declarar el tipo: el intérprete lo infiere automáticamente.

In [ ]:
x = 10        # Entero
y = 3.14      # Flotante
nombre = "Ana"  # Cadena de texto (string)
activo = True   # Booleano

#### Tipos de datos básicos

#### Enteros (`int`)

In [ ]:
a = 7
b = -4
print(a + b)   # 3
print(a * 2)   # 14

#### Flotantes (`float`)

In [ ]:
pi = 3.14159
radio = 5.0
area = pi * radio**2
print(area)   # 78.53975

#### Cadenas (`str`)

In [ ]:
saludo = "Hola"
nombre = "Lucas"
mensaje = saludo + " " + nombre
print(mensaje)   # Hola Lucas

Operaciones útiles con strings:

In [ ]:
texto = "Python"
print(texto.upper())    # PYTHON
print(texto.lower())    # python
print(len(texto))       # 6

#### Booleanos (`bool`)

In [ ]:
es_mayor = 10 > 3
print(es_mayor)   # True

es_igual = (5 == 2)
print(es_igual)   # False

#### Conversión de tipos

En Python puedes transformar valores de un tipo a otro:

In [ ]:
num = "100"
num_entero = int(num)     # de str a int
num_flotante = float(num) # de str a float
print(num_entero + 1)     # 101
print(num_flotante + 0.5) # 100.5

### 1.3 Estructuras de datos: listas, tuplas y diccionarios

#### Listas (`list`)

Una **lista** es una colección ordenada y mutable de elementos. Se definen con corchetes `[]`.

In [ ]:
numeros = [1, 2, 3, 4, 5]
mixta = [10, "hola", 3.14, True]

print(numeros[0])    # 1
print(mixta[1])      # hola

Operaciones comunes con listas:

In [ ]:
# Agregar y eliminar
numeros.append(6)     
print(numeros)        # [1, 2, 3, 4, 5, 6]

numeros.remove(3)
print(numeros)        # [1, 2, 4, 5, 6]

# Slicing
print(numeros[1:4])   # [2, 4, 5]

#### Tuplas (`tuple`)

Una **tupla** es una colección ordenada e inmutable. Se definen con paréntesis `()`.

In [ ]:
coordenada = (10, 20)
print(coordenada[0])   # 10

No se puede modificar
coordenada[0] = 15  -> Error

Las tuplas se usan cuando los datos no deben cambiar.

#### Diccionarios (`dict`)

Un **diccionario** es una colección no ordenada de pares **clave\:valor**. Se definen con llaves `{}`.

In [ ]:
estudiante = {
    "nombre": "Ana",
    "edad": 22,
    "activo": True
}

print(estudiante["nombre"])  # Ana

# Agregar un nuevo par clave-valor
estudiante["nota"] = 4.5
print(estudiante)

Operaciones útiles con diccionarios:

In [ ]:
# Obtener claves y valores
print(estudiante.keys())    # dict_keys(['nombre', 'edad', 'activo', 'nota'])
print(estudiante.values())  # dict_values(['Ana', 22, True, 4.5])

# Eliminar un elemento
del estudiante["activo"]
print(estudiante)

### 1.4 Control de flujo

#### Condicionales (`if`, `elif`, `else`)

Los condicionales permiten ejecutar bloques de código dependiendo de una condición.

In [ ]:
edad = 20

if edad >= 18:
    print("Eres mayor de edad")
elif edad > 12:
    print("Eres adolescente")
else:
    print("Eres niño")

#### Bucles `for`

El bucle `for` se utiliza para recorrer secuencias (listas, tuplas, diccionarios, rangos).

In [ ]:
for i in range(5):
    print("Iteración:", i)

Recorriendo una lista:

In [ ]:
frutas = ["manzana", "pera", "uva"]
for fruta in frutas:
    print(fruta)

#### Bucles `while`

El bucle `while` repite un bloque mientras se cumpla una condición.

In [ ]:
contador = 0
while contador < 3:
    print("Contador:", contador)
    contador += 1

#### `match-case` (Python 3.10+)

Es una forma de **estructuras condicionales múltiples**, similar al `switch` de otros lenguajes.

In [ ]:
opcion = 2

match opcion:
    case 1:
        print("Elegiste la opción 1")
    case 2:
        print("Elegiste la opción 2")
    case 3:
        print("Elegiste la opción 3")
    case _:
        print("Opción no válida")

También funciona con patrones más complejos:

In [ ]:
punto = (x, 5)

match punto:
    case (0, 0):
        print("Origen")
    case (0, y):
        print(f"Eje Y, coordenada {y}")
    case (x, 0):
        print(f"Eje X, coordenada {x}")
    case (x, y):
        print(f"Punto en el plano: ({x}, {y})")

### 1.5 Funciones

#### ¿Qué es una función?

Una **función** es un bloque de código reutilizable que se define con la palabra clave `def`.
Permite organizar el código y evitar repeticiones.

In [ ]:
def saludar():
    print("Hola desde una función")

saludar()

#### Funciones con parámetros

In [ ]:
def sumar(a, b):
    return a + b

resultado = sumar(5, 3)
print(resultado)   # 8

#### Parámetros por defecto

Se pueden asignar valores por defecto a los parámetros.

In [ ]:
def potencia(base, exponente=2):
    return base ** exponente

print(potencia(4))      # 16 (usa exponente=2)
print(potencia(4, 3))   # 64

#### Funciones con número variable de argumentos

* `*args` recibe una cantidad variable de argumentos en forma de tupla.
* `**kwargs` recibe argumentos nombrados en forma de diccionario.

In [ ]:
def mostrar_args(*args, **kwargs):
    print("args:", args)
    print("kwargs:", kwargs)

mostrar_args(1, 2, 3, nombre="Ana", edad=22)

#### Funciones anidadas

En Python se pueden definir funciones dentro de otras.

In [ ]:
def exterior(x):
    def interior(y):
        return y * y
    return interior(x) + 1

print(exterior(3))   # 10

#### Funciones lambda

Son funciones anónimas (sin nombre), útiles para operaciones pequeñas y rápidas.

In [ ]:
doble = lambda x: x * 2
print(doble(5))   # 10

Con más de un parámetro:

In [ ]:
suma = lambda a, b: a + b
print(suma(2, 3))   # 5

Uso con `sorted` y `map`:

In [ ]:
# Ordenar por longitud de palabra
palabras = ["sol", "estrella", "luz"]
ordenadas = sorted(palabras, key=lambda x: len(x))
print(ordenadas)   # ['sol', 'luz', 'estrella']

# Aplicar una operación a cada elemento
numeros = [1, 2, 3, 4]
cuadrados = list(map(lambda x: x**2, numeros))
print(cuadrados)   # [1, 4, 9, 16]

### 1.6 Clases y métodos

#### ¿Qué es una clase?

Una **clase** es una plantilla para crear objetos.
Los objetos tienen **atributos** (datos) y **métodos** (funciones asociadas).


#### Definiendo una clase simple

In [ ]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad
    
    def saludar(self):
        print(f"Hola, me llamo {self.nombre} y tengo {self.edad} años")

Uso:

In [ ]:
p1 = Persona("Ana", 22)
p1.saludar()

#### Atributos de instancia

Cada objeto puede tener valores distintos en sus atributos.

In [ ]:
p2 = Persona("Luis", 30)
print(p1.nombre)   # Ana
print(p2.nombre)   # Luis

#### Métodos de clase y métodos estáticos

* **Método de clase**: se define con `@classmethod` y recibe `cls` en lugar de `self`.
* **Método estático**: se define con `@staticmethod` y no recibe ni `self` ni `cls`.

In [ ]:
class Matematica:
    pi = 3.14159   # atributo de clase

    @classmethod
    def valor_pi(cls):
        return cls.pi

    @staticmethod
    def sumar(a, b):
        return a + b

Uso:

In [ ]:
print(Matematica.valor_pi())   # 3.14159
print(Matematica.sumar(5, 7))  # 12

#### Encapsulación (atributos privados)

En Python no existen privados estrictos, pero por convención se usa `_` o `__`.

In [ ]:
class CuentaBancaria:
    def __init__(self, titular, saldo):
        self.titular = titular
        self.__saldo = saldo  # atributo "privado"
    
    def mostrar_saldo(self):
        return self.__saldo

Uso:

In [ ]:
cuenta = CuentaBancaria("Ana", 1000)
print(cuenta.mostrar_saldo())   # 1000
#print(cuenta.__saldo)#  -> Error

#### Herencia básica

Una clase puede heredar de otra.

In [ ]:
class Estudiante(Persona):
    def __init__(self, nombre, edad, carrera):
        super().__init__(nombre, edad)
        self.carrera = carrera
    
    def presentarse(self):
        print(f"Soy {self.nombre}, estudio {self.carrera}")

Uso:

In [ ]:
e1 = Estudiante("Carlos", 19, "Ingeniería")
e1.saludar()       # método heredado
e1.presentarse()   # método propio

### 📌 Mini-proyecto: Gestor de Estudiantes

#### Objetivo

Construir un pequeño sistema que:

1. Permita crear estudiantes con nombre, edad y nota.
2. Guarde a los estudiantes en una lista.
3. Calcule estadísticas (promedio, mejor y peor nota).
4. Ordene estudiantes por nota usando una función lambda.
5. Use una clase con métodos para gestionar la información.


#### Código

## Numpy

### 2.1 ¿Qué es Numpy?

#### Introducción

**Numpy** (Numerical Python) es una librería fundamental para la computación científica en Python.
Sus principales características son:

* Proporciona el tipo de dato **array multidimensional** (`ndarray`), más eficiente que las listas de Python.
* Permite operaciones matemáticas **vectorizadas**, evitando bucles explícitos.
* Está implementada en C y Fortran, lo que la hace mucho más rápida que las estructuras nativas de Python.
* Es la base de otras librerías como **Pandas**, **Matplotlib**, **Scikit-learn** y **TensorFlow**.

---

#### Instalación

En la terminal o consola se instala con:

```bash
pip install numpy
```


#### Importación en Python

Por convención, Numpy se importa con el alias `np`:

```python
import numpy as np
```


#### Ejemplo básico

In [ ]:
import numpy as np

# Crear un array unidimensional
arr = np.array([1, 2, 3, 4, 5])
print(arr)        # [1 2 3 4 5]
print(type(arr))  # <class 'numpy.ndarray'>

### 2.2 Diferencias entre listas de Python y arrays de Numpy

#### Listas en Python

Las **listas** son estructuras flexibles que pueden contener elementos de distintos tipos.
Sin embargo, no están optimizadas para operaciones numéricas grandes.

In [ ]:
# Lista en Python
lista = [1, 2, 3, 4, 5]

# Multiplicar cada elemento por 2 usando un for
doble_lista = []
for x in lista:
    doble_lista.append(x * 2)

print(doble_lista)   # [2, 4, 6, 8, 10]

#### Arrays en Numpy

Los **arrays de Numpy** (`ndarray`) son estructuras homogéneas y optimizadas para cálculos matemáticos.
Permiten operaciones **vectorizadas** (sin bucles explícitos).

In [ ]:
# Array en Numpy
arr = np.array([1, 2, 3, 4, 5])

# Operación vectorizada
doble_arr = arr * 2
print(doble_arr)     # [ 2  4  6  8 10]

#### Ejemplo comparativo: suma de dos vectores

Con listas en Python:

In [ ]:
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]

suma = []
for i in range(len(a)):
    suma.append(a[i] + b[i])

print(suma)   # [11, 22, 33, 44, 55]

Con Numpy (vectorización):

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

suma = a + b
print(suma)   # [11 22 33 44 55]

#### Diferencia de rendimiento

Para operaciones grandes, Numpy es mucho más rápido.

In [ ]:
import time

# Con listas
lista = list(range(1_000_000))
start = time.time()
[ x * 2 for x in lista ]
end = time.time()
print("Tiempo con listas:", end - start)

# Con Numpy
arr = np.arange(1_000_000)
start = time.time()
arr * 2
end = time.time()
print("Tiempo con Numpy:", end - start)

> ⚡ Numpy suele ser **decenas de veces más rápido** porque las operaciones están implementadas en C y no en bucles de Python.

### 2.3 Creación de arrays en Numpy

Numpy ofrece múltiples formas de crear arrays según la necesidad.


#### A partir de listas o tuplas (`np.array`)

Convierte estructuras de Python en arrays de Numpy.

In [ ]:
lista = [1, 2, 3, 4, 5]
arr = np.array(lista)
print(arr)         # [1 2 3 4 5]
print(type(arr))   # <class 'numpy.ndarray'>

#### Arrays de ceros (`np.zeros`)

Crea un array lleno de ceros.

In [ ]:
zeros = np.zeros((3, 4))   # matriz de 3 filas y 4 columnas
print(zeros)

```
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
```

#### Arrays de unos (`np.ones`)

Crea un array lleno de unos.

In [ ]:
unos = np.ones((2, 5))   # 2 filas, 5 columnas
print(unos)

```
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
```

#### Rango de valores enteros (`np.arange`)

Similar a `range()` de Python, pero devuelve un `ndarray`.

In [ ]:
rango = np.arange(0, 10, 2)   # inicio=0, fin=10 (excluido), paso=2
print(rango)   # [0 2 4 6 8]

#### Espaciado lineal (`np.linspace`)

Crea un array con un número específico de puntos equiespaciados.

In [ ]:
linea = np.linspace(0, 1, 5)  # de 0 a 1 en 5 puntos
print(linea)   # [0.   0.25 0.5  0.75 1. ]

#### Ejemplo práctico: cuadrícula de puntos

In [ ]:
x = np.linspace(-1, 1, 5)
y = np.linspace(-1, 1, 5)

print("x:", x)
print("y:", y)

### 2.4 Indexación y slicing

Los arrays de Numpy permiten seleccionar y manipular subconjuntos de datos de manera muy eficiente.


#### Indexación básica

Acceso a elementos individuales (igual que en listas de Python).

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # 10 (primer elemento)
print(arr[-1])  # 50 (último elemento)

#### Slicing (rebanado)

Permite extraer rangos de elementos.

In [ ]:
print(arr[1:4])    # [20 30 40]
print(arr[:3])     # [10 20 30]
print(arr[2:])     # [30 40 50]

#### Indexación en 2D

En matrices se usan dos índices: `[fila, columna]`.

In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0, 0])   # 1 (fila 0, col 0)
print(mat[1, 2])   # 6 (fila 1, col 2)

#### Slicing en 2D

Podemos extraer submatrices.

In [ ]:
print(mat[:2, :2])   # submatriz 2x2 desde arriba a la izquierda
# [[1 2]
#  [4 5]]

print(mat[:, 1])     # segunda columna: [2 5 8]
print(mat[1, :])     # segunda fila: [4 5 6]

#### Indexación booleana

Permite filtrar elementos según una condición.

In [ ]:
valores = np.array([3, 7, 2, 9, 5])
print(valores[valores > 4])   # [7 9 5]

#### Indexación con listas de índices

Podemos seleccionar elementos específicos.

In [ ]:
indices = [0, 2, 4]
print(valores[indices])   # [3 2 5]

### 2.5 Operaciones vectorizadas vs bucles en Python

Una de las principales ventajas de **Numpy** es la **vectorización**: aplicar operaciones a todo un array sin necesidad de usar bucles explícitos.
Esto hace que el código sea más **rápido** y **conciso**.


#### Ejemplo 1: multiplicar cada elemento por 2

Con **listas en Python** (bucle):

In [ ]:
lista = [1, 2, 3, 4, 5]
doble_lista = [x * 2 for x in lista]
print(doble_lista)   # [2, 4, 6, 8, 10]

Con **Numpy (vectorizado)**:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
doble_arr = arr * 2
print(doble_arr)     # [ 2  4  6  8 10]

#### Ejemplo 2: operaciones matemáticas

En Python puro:

In [ ]:
import math

lista = [1, 2, 3, 4, 5]
raices = [math.sqrt(x) for x in lista]
print(raices)   # [1.0, 1.4142..., 1.732..., 2.0, 2.236...]

Con Numpy (vectorizado):

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
raices = np.sqrt(arr)
print(raices)   # [1.     1.4142 1.7320 2.     2.2360]

#### Ejemplo 3: comparación de rendimiento

Multiplicamos por 2 un millón de elementos.

In [ ]:
# Python nativo
lista = list(range(1_000_000))
start = time.time()
doble_lista = [x * 2 for x in lista]
end = time.time()
print("Tiempo con listas:", end - start)

# Numpy vectorizado
arr = np.arange(1_000_000)
start = time.time()
doble_arr = arr * 2
end = time.time()
print("Tiempo con Numpy:", end - start)

> ⚡ Numpy suele ser entre **10x y 100x más rápido** que un bucle en Python.

### 2.6 Broadcasting

El **broadcasting** es una característica poderosa de Numpy que permite realizar operaciones entre arrays de diferentes tamaños o dimensiones **sin necesidad de bucles explícitos**.

La idea es que Numpy "extiende" (broadcast) los arrays más pequeños para que coincidan con la forma del más grande.


#### Ejemplo 1: suma de un escalar a un array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)   # [11 12 13 14 15]

Aquí, el número `10` se "expande" para sumarse a cada elemento del array.


#### Ejemplo 2: suma de un vector a una matriz

In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

vec = np.array([10, 20, 30])

print(mat + vec)

Resultado:

```
[[11 22 33]
 [14 25 36]
 [17 28 39]]
```

El vector `vec` se **replica por filas** para que coincida con la matriz.


#### Ejemplo 3: broadcasting con distintas dimensiones

In [ ]:
columna = np.array([[1],
                    [2],
                    [3]])   # forma (3,1)

fila = np.array([10, 20, 30])  # forma (3,)

print(columna + fila)

Resultado:

```
[[11 21 31]
 [12 22 32]
 [13 23 33]]
```

Aquí, Numpy expande `columna` en horizontal y `fila` en vertical para que ambas se ajusten a una forma `(3,3)`.


#### Reglas de broadcasting

1. Si las dimensiones son diferentes, Numpy añade dimensiones de tamaño 1 a la izquierda.
2. Si en alguna dimensión los tamaños son distintos y no hay un `1`, la operación falla.
3. Si un tamaño es `1`, se **expande** para igualar al del otro array.

### 2.7 Funciones estadísticas en Numpy

Numpy incluye funciones optimizadas para realizar operaciones estadísticas directamente sobre arrays, evitando bucles manuales.


#### Suma de elementos (`np.sum`)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))   # 15

#### Máximo y mínimo (`np.max`, `np.min`)

In [ ]:
print(np.max(arr))   # 5
print(np.min(arr))   # 1

#### Media aritmética (`np.mean`)

In [ ]:
print(np.mean(arr))  # 3.0

#### Desviación estándar (`np.std`)

In [ ]:
print(np.std(arr))   # 1.4142135623730951

#### Varianza (`np.var`)

In [ ]:
print(np.var(arr))   # 2.0

#### Operaciones en matrices

Todas estas funciones aceptan el argumento `axis` para calcular resultados **por filas** o **por columnas**.

In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(np.sum(mat))           # 45 (suma total)
print(np.sum(mat, axis=0))   # [12 15 18] (suma por columnas)
print(np.sum(mat, axis=1))   # [ 6 15 24] (suma por filas)

print(np.mean(mat, axis=0))  # [4. 5. 6.]
print(np.mean(mat, axis=1))  # [2. 5. 8.]

#### Ejemplo práctico: calificaciones de estudiantes

In [ ]:
notas = np.array([[3.5, 4.0, 4.2],
                  [2.8, 3.7, 3.9],
                  [4.5, 4.8, 5.0]])

promedio_estudiantes = np.mean(notas, axis=1)  # promedio de cada estudiante
promedio_examenes = np.mean(notas, axis=0)     # promedio de cada examen

print("Promedios por estudiante:", promedio_estudiantes)
print("Promedios por examen:", promedio_examenes)

### 📝 Mini-proyecto: Comparación de rendimiento y simulación de dados

Este ejercicio tiene **dos partes**:

1. Comparar la velocidad entre operaciones en listas de Python y arrays de Numpy.
2. Simular lanzamientos de dados usando Numpy.


### Parte 1: Comparación de rendimiento

**Objetivo**: Medir cuánto más rápido es Numpy frente a Python puro en operaciones numéricas.

💡 Preguntas para discusión:

* ¿Qué método fue más rápido?
* ¿Por qué Numpy logra esa diferencia?

### Parte 2: Simulación de lanzamientos de dados

**Objetivo**: Usar Numpy para simular fenómenos aleatorios.